name: Get Next Version
description: Get the next version from the commits
outputs:
  next-version:
    description: The next version that will be release (empty if none detected)
runs:
  using: node16
  main: index.js