name: Pipeline
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  test-actions:
    uses: ./.github/workflows/test-actions.yml

  build:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.0.2'
          enable-stack: true
          stack-version: latest
      - name: Run Tests
        run: stack test
      - name: Build
        run: stack build
      - name: Rename the binary to ${{ matrix.binary }}
        run: ${{ matrix.prepare }} ${{ matrix.binary }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            prepare: mv "$(stack exec -- which haskell-github-pipeline-exe)"
            binary: haskell-github-pipeline-x86_64-apple-darwin
          - os: ubuntu-latest
            prepare: mv "$(stack exec -- which haskell-github-pipeline-exe)"
            binary: haskell-github-pipeline-x86_64-unknown-linux-gnu
          - os: windows-latest
            prepare: mv "$(stack exec -- which haskell-github-pipeline.exe)"
            binary: haskell-github-pipeline-x86_64-pc-windows-msvc.exe

  verify-next-version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - test-actions
    outputs:
      next-version: ${{ steps.get-next-version.outputs.next-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Uplift
        uses: gembaadvantage/uplift-action@v2
        with:
          version: latest
          install-only: true
          args: version
      - name: Get Next Version
        id: get-next-version
        uses: tomphp/haskell-github-pipeline/.github/actions/get-next-version@main
      - name: Print Next Version
        shell: bash
        run: echo ${{ steps.get-next-version.outputs.next-version }}

  release:
    if: github.ref == 'refs/heads/main' && needs.verify-next-version.outputs.next-version != ''
    needs:
      - build
      - verify-next-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install uplift
        uses: gembaadvantage/uplift-action@v2
        with:
          version: latest
          install-only: true
          args: version
      - name: Bump version
        run: uplift release --fetch-all --no-push
      - name: Configure Git with last committer
        run: |
          git config user.name "$(git log -1 --pretty=format:"%an")"
          git config user.email "$(git log -1 --pretty=format:'%ae')"
      - name: Add bumped files to commit
        run: |
          git add package.yaml
          git commit --amend --no-edit