name: Pipeline
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test-actions:
    uses: ./.github/workflows/test-actions.yml

  build-and-release:
    uses: ./.github/workflows/build-and-release.yml
    with:
      app-name: haskell-github-pipeline